#!/usr/bin/env python3
"""
One original sentence under the verse — the only text on this account that is ours.

WHY THIS EXISTS. On 2026-09-14 Instagram had the account under a 퍼온 콘텐츠 (unoriginal
content) reach restriction, and the flagged posts were that week's, not the old duplicates:
신명기 1:29 was eight hours old and every pixel of it had been generated by our own
Higgsfield/Veo/Lyria run. The remedy Instagram offered — "invite the ORIGINAL CREATOR to
collaborate" — means it believes another account published it first, which cannot be true of
the video. So the match is on text, and the text is where this account owns nothing:

    caption        개역개정 verse + [reference]   ← thousands of 말씀 accounts post the same string
    overlay        the same verse                ← same
    first comment  fixed CTA + fixed hashtags    ← identical on every post

A machine reading this account finds not one original character. This module adds one.

OFF BY DEFAULT. Rule B-5 says the caption is the 말씀 and its source and nothing else, and
that is the account owner's rule to change, not this file's. Set CAPTION_REFLECTION=1 to
enable. With it unset, build_caption() produces the exact bytes it always has.

    python3 reflection.py "여호와는 나의 목자시니 내게 부족함이 없으리로다" "시편 23:1"
"""

import json
import os
import re
import urllib.request

MODEL = "gemini-2.5-pro"
ATTEMPTS = 3            # an empty answer is transient — 1 in 4 on the first real run
MIN_CHARS = 12          # shorter than this is not a thought ("좋다." passed the first version)
MAX_CHARS = 60          # one line. Longer competes with the 말씀, which always leads (rule A).

# The register is the account's, not a devotional blog's: quiet, present tense, no exclamation,
# no second-person command, no selling, no "오늘도 ~하세요". It says one true thing about the
# verse and stops. Examples are from real posts, so the model has the cadence rather than a
# description of it.
_PROMPT = """다음 성경 구절을 인스타그램에 올립니다. 구절 아래에 붙일 **한 문장**을 쓰세요.

구절: {text}
출처: {ref}

규칙:
- 정확히 한 문장, {max}자 이내.
- 조용한 평서문. 느낌표 없음. 명령형 없음("~하세요", "~합시다" 금지).
- 권유·홍보·질문 없음. 해시태그·이모지 없음.
- 구절을 다시 말하지 말고, 구절이 **무엇을 뒤집는지** 한 가지만 말할 것.
- 문장만 출력. 따옴표나 설명 없이.

예:
구절: 내가 너희에게 말하기를 그들을 무서워하지 말라 두려워하지 말라 / 신명기 1:29
→ 두려움이 사라져서가 아니라, 먼저 가시는 분이 계셔서 건너갑니다.

구절: 평안의 매는 줄로 성령이 하나 되게 하신 것을 힘써 지키라 / 에베소서 4:3
→ 하나 됨은 만드는 것이 아니라, 이미 주신 것을 지키는 일입니다."""

_BANNED = ("!", "?", "#", "팔로우", "구독", "공유", "좋아요")
# Imperatives by ENDING, not by substring. A banned-word list containing "하세요" happily passes
# "오늘도 힘내세요." — the account never tells the reader what to do, so match the verb ending.
# "삽시다"/"갑시다" hide the ㅂ inside the syllable, so a literal "합시다" misses them — match the
# ENDING "시다" instead. It can also reject a rare valid line ("…그 자리에 계시다."), and that is
# the right trade: a rejection is today's caption, a false accept is a sermon on the account.
_IMPERATIVE = re.compile(r"(시다|세요|십시오|해요|하자|자)\.?$")


def enabled():
    """Rule B-5 is the account owner's. Until it is changed this returns False and the caption
    is byte-identical to what it has always been."""
    return os.environ.get("CAPTION_REFLECTION", "").strip() in ("1", "true", "yes", "on")


def _clean(raw):
    """The model's answer → one publishable line, or None if it is not one.

    Rejecting is the safe outcome: a caption with no reflection is exactly today's caption,
    while a caption with a bad one is on the account until someone notices."""
    line = (raw or "").strip().split("\n")[0].strip()
    line = line.strip('"“”\'').removeprefix("→").strip()
    line = re.sub(r"\s+", " ", line)
    if not MIN_CHARS <= len(line) <= MAX_CHARS:
        return None
    if any(b in line for b in _BANNED) or _IMPERATIVE.search(line):
        return None
    if not line.endswith("."):            # a fragment, or the model kept talking
        return None
    return line


def line(verse):
    """One original sentence for `verse`, or None.

    Best-effort by construction: ANY failure — no key, API down, a line that breaks the
    register — returns None and the caller falls back to the verse-only caption. This must
    never be able to stop a post; the reach problem it addresses is smaller than a missed day.
    """
    if not enabled():
        return None
    # A thinking model sometimes answers with no `parts` at all (the budget went to reasoning),
    # which measured 1 in 4 on the first real run. That is a transient, not a verdict, so ask
    # again before giving up — the same reason the publish path retries 2207076.
    for attempt in range(ATTEMPTS):
        try:
            import fetch_higgsfield as hf
            body = {"contents": [{"parts": [{"text": _PROMPT.format(
                        text=verse["text"], ref=verse["ref"], max=MAX_CHARS)}]}],
                    "generationConfig": {"temperature": 0.9, "maxOutputTokens": 4096}}
            url = (f"https://generativelanguage.googleapis.com/v1beta/models/"
                   f"{MODEL}:generateContent?key={hf._gemini_key()}")
            req = urllib.request.Request(url, data=json.dumps(body).encode(),
                                         headers={"Content-Type": "application/json"}, method="POST")
            data = json.load(urllib.request.urlopen(req, timeout=90))
            parts = (data.get("candidates") or [{}])[0].get("content", {}).get("parts") or []
            got = _clean(parts[0].get("text") if parts else "")
            if got:
                print(f"reflection: {got}")
                return got
            print(f"reflection attempt {attempt + 1}: no usable line")
        except Exception as e:
            print(f"reflection attempt {attempt + 1} failed ({e})")
    print("reflection: none after retries → verse-only caption")
    return None


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 2:
        os.environ.setdefault("CAPTION_REFLECTION", "1")
        print(line({"text": sys.argv[1], "ref": sys.argv[2]}))
    else:
        for case in ("좋다.", "오늘도 힘내세요.", "정말 놀랍지 않나요?", "x" * 80,
                     "두려움이 사라져서가 아니라, 먼저 가시는 분이 계셔서 건너갑니다."):
            print(f"{case[:34]:<36} → {_clean(case)}")
